swagger: '2.0'
info:
  title: "My API"
  description: API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /getType:
    get:
      operationId: getMoviesList
      x-google-backend:
        address: https://get-movies-func-nw2z6mefba-lz.a.run.app
      summary: Get List Of Movies
      parameters:
        - name: endpoint
          in: query
          description: Type of Movie List To Retrieve
          required: false
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /search:
    get:
      operationId: getSearchMovies
      x-google-backend:
        address: https://search-movie-func-nw2z6mefba-lz.a.run.app
      summary: Get List Of Searched Movies
      parameters:
        - name: movieTitle
          in: query
          description: Movie Title To Search
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string