name: Deploy Cloud Functions

on:
  push :
    branches: [main]
    paths:
    - 'functions/get-movies-func/**'
    
  workflow_dispatch:   
    
env:
  PROJECT: ${{secrets.GC_PROJECT_ID}}
          
jobs:
  function_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.1.1
      with:
        project_id: ${{env.PROJECT}}
        credentials_json: ${{secrets.GCLOUD_AUTH}}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Deploy Get Movies function
      run: > 
        gcloud
        functions
        deploy
        get-movies-func
        --region=europe-north1
        --runtime=java17
        --gen2
        --trigger-http   
        --source=./functions/get-movies-func
        --entry-point=getmovies.GetMovies
        --allow-unauthenticated 
        --set-env-vars TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}
#unauthenticated is there for testing purposes

    - name: Deploy Cloud Search Function
      run: |
        gcloud functions deploy search-movie-func \
          --entry-point searchmovie.SearchMovie \
          --source=./functions/search-movie-func \
          --runtime java17 \
          --trigger-http \
          --allow-unauthenticated \
          --region europe-north1 \
          --project ${{ secrets.GC_PROJECT_ID }} \
          --gen2 \
          --set-env-vars TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}  # Set the environment variable