
name: build of get movies function on pull request

on:
  pull_request:
    branches: [main]  
    paths:
    - 'functions/**'
    
  workflow_dispatch:   
          
jobs:
  build_get_movies_func:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven   
    - name: Run the Maven verify, build and test
      run: cd functions/get-movies-func && mvn --batch-mode --update-snapshots verify

  build_search_movie_func:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven   
    - name: Run the Maven verify, build and test
      run: cd functions/search-movie-func && mvn --batch-mode --update-snapshots verify

  build_store_users_neo4j_func:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USER }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}  
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven   
    - name: Run the Maven verify, build and test
      run: cd functions/store-users-neo4j-func && mvn --batch-mode --update-snapshots verify

  build_get_cast_and_trailer_func:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven   
    - name: Run the Maven verify, build and test
      run: cd functions/get-cast-and-trailer-func && mvn --batch-mode --update-snapshots verify

  build_movie_lists_func:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USER }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}  
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify, build and test
        run: cd functions/movie-lists-func && mvn --batch-mode --update-snapshots verify

  build_retreive_lists_func:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USER }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify, build and test
        run: cd functions/retreive-lists-func && mvn --batch-mode --update-snapshots verify

  build_comment_func:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify, build and test
        run: cd functions/comment-func && mvn --batch-mode --update-snapshots verify

  build_get_delete_comments_func:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify, build and test
        run: cd functions/get-delete-comments-func && mvn --batch-mode --update-snapshots verify

  build_random_movies_func:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify, build and test
        run: cd functions/random-movies-func && mvn --batch-mode --update-snapshots verify

