
name: build of get movies function on pull request

on:
  pull_request:
    branches: [main]  
    paths:
    - 'functions/get-movies-func/**'
    
  workflow_dispatch:   
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven   
    - name: Run the Maven verify phase
      run: cd functions/get-movies-func && mvn --batch-mode --update-snapshots verify
    - name: MVN Compile
      run: cd functions/get-movies-func && mvn compile
    - name: Build with Maven
      run: cd functions/get-movies-func && mvn --batch-mode package --file pom.xml
    - name: MVN Test
      run: cd functions/get-movies-func && mvn test

