name: Deploy Static Web App

on:
  push:
    branches:
      - main
    paths:
      - webapp/** # include subdirectories as well

  # possibility to run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify URL placeholder values # replace with secret
        run: |
          sed -i "s#URL_GET_TYPE_PLACEHOLDER#${{ secrets.URL_GET_TYPE_PLACEHOLDER }}#g" webapp/script.js
          sed -i "s#URL_SEARCH_PLACEHOLDER#${{ secrets.URL_SEARCH_PLACEHOLDER }}#g" webapp/search.js
          sed -i "s#URL_CAST_TRAILER_PLACEHOLDER#${{ secrets.URL_CAST_TRAILER_PLACEHOLDER }}#g" webapp/moviePopup.js
          sed -i "s#URL_CREATE_USER_PLACEHOLDER#${{ secrets.URL_CREATE_USER_PLACEHOLDER }}#g" webapp/login.js
          sed -i "s#URL_MOVIE_LISTS_PLACEHOLDER#${{ secrets.URL_MOVIE_LISTS_PLACEHOLDER }}#g" webapp/icons.js
          sed -i "s#URL_RETRIEVE_LISTS_PLACEHOLDER#${{ secrets.URL_RETRIEVE_LISTS_PLACEHOLDER }}#g" webapp/retrieveLists.js
          sed -i "s#URL_RANDOM_MOVIES_PLACEHOLDER#${{ secrets.URL_RANDOM_MOVIES_PLACEHOLDER }}#g" webapp/random.js
          sed -i "s#URL_POST_COMMENTS_PLACEHOLDER#${{ secrets.URL_POST_COMMENTS_PLACEHOLDER }}#g" webapp/commentbox.js
          sed -i "s#URL_GET_DEL_COMMENTS#${{ secrets.URL_GET_DEL_COMMENTS }}#g" webapp/moviePopup.js

      - name: Replace Firebase placeholder values
        run: |
          sed -i "s#FIREBASE_API_KEY#${{ secrets.FIREBASE_API_KEY }}#g" webapp/login.js
          sed -i "s#FIREBASE_AUTH_DOMAIN#${{ secrets.FIREBASE_AUTH_DOMAIN }}#g" webapp/login.js
          sed -i "s#FIREBASE_PROJECT_ID#${{ secrets.FIREBASE_PROJECT_ID }}#g" webapp/login.js
          sed -i "s#FIREBASE_STORAGE_BUCKET#${{ secrets.FIREBASE_STORAGE_BUCKET }}#g" webapp/login.js    
          sed -i "s#FIREBASE_MESSAGING_SEND_ID#${{ secrets.FIREBASE_MESSAGING_SEND_ID }}#g" webapp/login.js
          sed -i "s#FIREBASE_APP_ID#${{ secrets.FIREBASE_APP_ID }}#g" webapp/login.js
          sed -i "s#FIREBASE_MEASURE_ID#${{ secrets.FIREBASE_MEASURE_ID }}#g" webapp/login.js

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}

      - name: Deploy web app to Google Cloud Storage
        run: |
          gsutil cp -r ./webapp/* gs://best-movies/