name: Deploy Static Web App

on:
  push:
    branches:
      - main
    paths:
      - webapp/** # include subdirectories as well

  # possibility to run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify placeholder values # replace with secret
        run: |
          sed -i "s#URL_GET_TYPE_PLACEHOLDER#${{ secrets.URL_GET_TYPE_PLACEHOLDER }}#g" webapp/script.js
          sed -i "s#URL_SEARCH_PLACEHOLDER#${{ secrets.URL_SEARCH_PLACEHOLDER }}#g" webapp/search.js
          sed -i "s#URL_CAST_TRAILER_PLACEHOLDER#${{ secrets.URL_CAST_TRAILER_PLACEHOLDER }}#g" webapp/moviePopup.js

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}

      - name: Deploy web app to Google Cloud Storage
        run: |
          gsutil cp -r ./webapp/* gs://best-movies/